In [7]:
import numpy as np
import pandas as pd
from kmodes.kmodes import KModes
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage
from scipy.cluster.hierarchy import fcluster

# Example categorical data
data = pd.read_csv('DATA/Truck_drivers_final.csv')
sampled_data = data.sample(n=10000, random_state=42)

if sampled_data.isnull().any().any():
    print("Data contains NaN values. Handling NaNs...")
    sampled_data = sampled_data.fillna(method='ffill').fillna(method='bfill')
sampled_data

Data contains NaN values. Handling NaNs...

,accident_type,gender,nationality,work_situation,main_occupation,seniority_in_the_job_months,seniority_in_the_job_days,contract_type,social_security_regime,economic_activity_center,...,injury_severity_discharged,discharge_date,diagnoses_code,leave_duration,age,year_accident,DateColumn_accident,DateColumn_medical_leave,DateColumn_discharge,Quarter
74547,1,1,724,1,843,Experienced,0,100,1,494,...,1.0,7032014.0,7242,5,46-55,2014,2014-03-03,2014-03-03,2014-03-07,1
182537,1,1,724,1,843,New hires,0,189,1,494,...,1.0,12062020.0,8450,9,36-45,2020,2020-06-03,2020-06-04,2020-06-12,2
110833,1,1,724,1,843,Junior employees,0,401,1,494,...,1.0,9082013.0,71783,185,26-35,2013,2013-02-04,2013-02-06,2013-08-09,1
86981,1,1,724,1,843,Veterans,0,100,1,494,...,1.0,12092014.0,84502,11,46-55,2014,2014-09-01,2014-09-02,2014-09-12,3
166768,1,1,724,1,843,New hires,26,100,1,381,...,1.0,5082019.0,71946,13,36-45,2019,2019-07-24,2019-07-24,2019-08-05,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177720,1,1,724,1,843,Junior employees,0,389,1,494,...,1.0,30052020.0,95911,6,+56,2020,2020-05-22,2020-05-25,2020-05-30,2
166386,1,2,724,1,843,Veterans,0,189,1,383,...,1.0,15112019.0,7231,10,36-45,2019,2019-11-05,2019-11-06,2019-11-15,4
67328,1,1,724,1,843,Experienced,0,100,1,494,...,1.0,27112013.0,8441,17,+56,2013,2013-11-10,2013-11-11,2013-11-27,4
179755,1,1,724,1,843,Veterans,0,100,1,463,...,1.0,27012020.0,92311,17,+56,2020,2020-01-11,2020-01-11,2020-01-27,1
78973,1,1,724,1,843,Junior employees,0,100,1,494,...,1.0,23102015.0,92410,45,46-55,2015,2015-09-09,2015-09-09,2015-10-23,3

In [6]:
import numpy as np
import pandas as pd
from kmodes.kmodes import KModes
import matplotlib.pyplot as plt
from scipy.cluster.hierarchy import dendrogram, linkage
from scipy.cluster.hierarchy import fcluster

# Example categorical data
data = pd.read_csv('DATA/Truck_drivers_final.csv')
sampled_data = data.sample(n=10000, random_state=42)

if sampled_data.isnull().any().any():
    print("Data contains NaN values. Handling NaNs...")
    sampled_data = sampled_data.fillna(method='ffill').fillna(method='bfill')
# Perform k-modes clustering

# Perform k-modes clustering on the sampled data
from kmodes.kmodes import KModes

km = KModes(n_clusters=3, init='Huang', n_init=5, verbose=1)
clusters = km.fit_predict(sampled_data)

print("Cluster centroids:\n", km.cluster_centroids_)
print("Cluster labels:", clusters)

# Plotting the results is the same as before
print("Cluster centroids:\n", km.cluster_centroids_)
print("Cluster labels:", clusters)

# Add cluster labels to data
sampled_data['cluster'] = clusters

# Calculate distance matrix using matching dissimilarity
def matching_dissim(a, b):
    return np.sum(a != b, axis=1)

centroids = km.cluster_centroids_
distance_matrix = np.zeros((len(sampled_data), len(sampled_data)))

for i in range(len(sampled_data)):
    for j in range(i + 1, len(sampled_data)):
        distance = matching_dissim(sampled_data.iloc[i, :-1].values, sampled_data.iloc[j, :-1].values)
        distance_matrix[i, j] = distance
        distance_matrix[j, i] = distance

# Perform hierarchical/agglomerative clustering on the distance matrix
Z = linkage(distance_matrix, method='average')

# Plot dendrogram
plt.figure(figsize=(10, 7))
plt.title('Hierarchical Clustering Dendrogram')
plt.xlabel('Sample index')
plt.ylabel('Distance')
dendrogram(Z, labels=sampled_data.index.tolist(), leaf_rotation=90., leaf_font_size=10.)
plt.show()

# Form flat clusters
max_d = 1.5  # Distance threshold
flat_clusters = fcluster(Z, max_d, criterion='distance')

print("Flat cluster labels:", flat_clusters)

Data contains NaN values. Handling NaNs...
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 1, iteration: 1/100, moves: 4008, cost: 270114.0
Run 1, iteration: 2/100, moves: 432, cost: 270110.0
Run 1, iteration: 3/100, moves: 0, cost: 270110.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 2, iteration: 1/100, moves: 3693, cost: 268469.0
Run 2, iteration: 2/100, moves: 366, cost: 268464.0
Run 2, iteration: 3/100, moves: 2, cost: 268464.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 3, iteration: 1/100, moves: 2707, cost: 271146.0
Run 3, iteration: 2/100, moves: 129, cost: 271146.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 4, iteration: 1/100, moves: 3222, cost: 269318.0
Run 4, iteration: 2/100, moves: 1693, cost: 268563.0
Run 4, iteration: 3/100, moves: 476, cost: 268563.0
Init: initializing centroids
Init: initializing clusters
Starting iterations...
Run 5, iteration: 1/100, moves: 3482, cost: 270082.0
Run 5, iteration: 2/100, moves: 316, cost: 270079.0
Run 5, iteration: 3/100, moves: 0, cost: 270079.0
Best run was number 2
Cluster centroids:
 [['1' '1' '724' '1' '843' 'Veterans' '0' '100' '1' '494' '1' '28' '0' '0'
  '0' '0' '0' '0' '1' '0' '1' '0' '1' '1' '0' '0' '0' '28' '3' '494'
  '5092011' '21072011' '3' '11' 'Worked between 3 to 6 hours' '1' '1'
  '13' '12' 'Movement' '12010000'
  'Falling persons – Slip or trip and fall' '12010000' '31' '12010000'
  '0' 'Wounds and superficial injuries' 'mild' 'Inferior limbs' '2' '0'
  '23.61' '1.0' '31072020.0' '9248' '8' '46-55' '2011' '2011-09-05'
  '2011-07-21' '2020-07-31' '3']
 ['1' '1' '724' '1' '843' 'New hires' '0' '100' '1' '494' '1' '8' '0' '0'
  '0' '0' '0' '0' '1' '0' '1' '0' '1' '1' '0' '0' '0' '8' '4' '494'
  '11062018' '11062018' '1' '9' 'Recently started working' '1' '1' '61'
  '61' 'Movement' '12010100'
  'Movement of the body without added physical effort' '12010100' '71'
  '12010100' '0' 'Dislocations, sprains and strains' 'mild'
  'Inferior limbs' '2' '0' '23.61' '1.0' '6072018.0' '7242' '5' '36-45'
  '2019' '2018-06-11' '2018-06-11' '2018-07-06' '2']
 ['1' '1' '724' '1' '843' 'New hires' '0' '100' '1' '494' '5' '28' '0'
  '0' '0' '0' '0' '0' '1' '0' '1' '0' '1' '1' '0' '0' '0' '28' '5' '494'
  '11102016' '10122018' '2' '10' 'Worked between 3 to 6 hours' '1' '1'
  '13' '12' 'Object manipulation' '14120000'
  'Movement of the body as a result of or with physical effort'
  '14120000' '71' '14120000' '0' 'Dislocations, sprains and strains'
  'mild' 'Superior limbs' '2' '0' '37.76' '1.0' '6032020.0' '7242' '8'
  '36-45' '2016' '2016-10-11' '2012-06-19' '2020-03-06' '4']]
Cluster labels: [1 0 1 ... 0 0 0]
Cluster centroids:
 [['1' '1' '724' '1' '843' 'Veterans' '0' '100' '1' '494' '1' '28' '0' '0'
  '0' '0' '0' '0' '1' '0' '1' '0' '1' '1' '0' '0' '0' '28' '3' '494'
  '5092011' '21072011' '3' '11' 'Worked between 3 to 6 hours' '1' '1'
  '13' '12' 'Movement' '12010000'
  'Falling persons – Slip or trip and fall' '12010000' '31' '12010000'
  '0' 'Wounds and superficial injuries' 'mild' 'Inferior limbs' '2' '0'
  '23.61' '1.0' '31072020.0' '9248' '8' '46-55' '2011' '2011-09-05'
  '2011-07-21' '2020-07-31' '3']
 ['1' '1' '724' '1' '843' 'New hires' '0' '100' '1' '494' '1' '8' '0' '0'
  '0' '0' '0' '0' '1' '0' '1' '0' '1' '1' '0' '0' '0' '8' '4' '494'
  '11062018' '11062018' '1' '9' 'Recently started working' '1' '1' '61'
  '61' 'Movement' '12010100'
  'Movement of the body without added physical effort' '12010100' '71'
  '12010100' '0' 'Dislocations, sprains and strains' 'mild'
  'Inferior limbs' '2' '0' '23.61' '1.0' '6072018.0' '7242' '5' '36-45'
  '2019' '2018-06-11' '2018-06-11' '2018-07-06' '2']
 ['1' '1' '724' '1' '843' 'New hires' '0' '100' '1' '494' '5' '28' '0'
  '0' '0' '0' '0' '0' '1' '0' '1' '0' '1' '1' '0' '0' '0' '28' '5' '494'
  '11102016' '10122018' '2' '10' 'Worked between 3 to 6 hours' '1' '1'
  '13' '12' 'Object manipulation' '14120000'
  'Movement of the body as a result of or with physical effort'
  '14120000' '71' '14120000' '0' 'Dislocations, sprains and strains'
  'mild' 'Superior limbs' '2' '0' '37.76' '1.0' '6032020.0' '7242' '8'
  '36-45' '2016' '2016-10-11' '2012-06-19' '2020-03-06' '4']]
Cluster labels: [1 0 1 ... 0 0 0]

AxisError: axis 1 is out of bounds for array of dimension 1